"""Plot grouped qpos curves from an existing RGB-D retargeting pickle.

This script does not run hand detection or retargeting. It reads the pickle
generated by detect_from_rgbd.py and saves a grouped multi-subplot PNG:

  - wrist translation qpos[0:3]
  - wrist rotation qpos[3:6]
  - finger joints grouped by joint names
"""

import argparse
import os
import pickle
from collections import OrderedDict
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")
os.environ.setdefault("XDG_CACHE_HOME", "/tmp")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np


FingerGroups = Dict[str, List[int]]


FINGER_KEYWORDS: Tuple[Tuple[str, Tuple[str, ...]], ...] = (
    ("Thumb", ("thumb",)),
    ("Index", ("index",)),
    ("Middle", ("middle",)),
    ("Ring", ("ring",)),
    ("Little", ("little", "pinky", "pinky_finger", "small")),
)


def _load_qpos_data(pickle_path: str) -> Tuple[np.ndarray, List[str]]:
    with open(pickle_path, "rb") as f:
        result = pickle.load(f)

    frames = result.get("data", [])
    if len(frames) == 0:
        raise ValueError(f"No frame data found in {pickle_path}")

    qpos_list = []
    for frame_id, frame in enumerate(frames):
        if "qpos" not in frame:
            raise ValueError(f"Frame {frame_id} does not contain a 'qpos' field")
        qpos_list.append(np.asarray(frame["qpos"], dtype=np.float64))

    qpos_array = np.asarray(qpos_list, dtype=np.float64)
    if qpos_array.ndim != 2:
        raise ValueError(f"Expected qpos array to be 2D, got shape {qpos_array.shape}")

    dof = qpos_array.shape[1]
    meta_data = result.get("meta_data", {})
    joint_names = list(meta_data.get("joint_names", []))
    if len(joint_names) < dof:
        joint_names.extend(f"joint_{i}" for i in range(len(joint_names), dof))
    elif len(joint_names) > dof:
        joint_names = joint_names[:dof]

    return qpos_array, joint_names


def _find_wrist_indices(joint_names: Sequence[str], dof: int) -> Tuple[List[int], List[int]]:
    lower_names = [name.lower() for name in joint_names]

    translation = [
        i
        for i, name in enumerate(lower_names)
        if "translation" in name or name.endswith("_x") or name.endswith("_y") or name.endswith("_z")
    ]
    rotation = [i for i, name in enumerate(lower_names) if "rotation" in name]

    # RGB-D position retargeting configs commonly put the dummy 6DoF wrist first.
    if len(translation) < 3 and dof >= 3:
        translation = [0, 1, 2]
    if len(rotation) < 3 and dof >= 6:
        rotation = [3, 4, 5]

    return translation[:3], rotation[:3]


def _group_finger_joints(
    joint_names: Sequence[str],
    start_index: int,
    include_other: bool,
) -> FingerGroups:
    groups: FingerGroups = OrderedDict((group_name, []) for group_name, _ in FINGER_KEYWORDS)
    other: List[int] = []

    for joint_index in range(start_index, len(joint_names)):
        lower_name = joint_names[joint_index].lower()
        matched_group = None
        for group_name, keywords in FINGER_KEYWORDS:
            if any(keyword in lower_name for keyword in keywords):
                matched_group = group_name
                break

        if matched_group is None:
            other.append(joint_index)
        else:
            groups[matched_group].append(joint_index)

    groups = OrderedDict((name, indices) for name, indices in groups.items() if indices)
    if include_other and other:
        groups["Other"] = other

    return groups


def _convert_angle_values(values: np.ndarray, unit: str) -> np.ndarray:
    if unit == "deg":
        return np.rad2deg(values)
    return values


def _plot_lines(
    ax: plt.Axes,
    frames: np.ndarray,
    qpos_array: np.ndarray,
    joint_names: Sequence[str],
    joint_indices: Iterable[int],
    title: str,
    ylabel: str,
    unit: str,
    convert_angles: bool,
) -> None:
    for joint_index in joint_indices:
        values = qpos_array[:, joint_index]
        if convert_angles:
            values = _convert_angle_values(values, unit)
        ax.plot(frames, values, linewidth=1.4, label=f"{joint_names[joint_index]} ({joint_index})")

    ax.set_title(title)
    ax.set_xlabel("Frame")
    ax.set_ylabel(ylabel)
    ax.grid(True, linestyle="--", alpha=0.45)
    ax.legend(loc="best", fontsize=8)


def plot_grouped_qpos_curves(
    pickle_path: str,
    save_path: str,
    unit: str = "rad",
    include_wrist: bool = True,
    include_fingers: bool = True,
    include_other: bool = True,
    fig_width: float = 14.0,
    fig_height_per_row: float = 2.8,
    dpi: int = 150,
) -> None:
    """Plot grouped qpos curves from a retargeting pickle and save a PNG."""
    if unit not in {"rad", "deg"}:
        raise ValueError("unit must be either 'rad' or 'deg'")

    qpos_array, joint_names = _load_qpos_data(pickle_path)
    num_frames, dof = qpos_array.shape
    frames = np.arange(num_frames)

    wrist_translation, wrist_rotation = _find_wrist_indices(joint_names, dof)
    finger_start = max(wrist_translation + wrist_rotation, default=-1) + 1
    finger_groups = _group_finger_joints(joint_names, finger_start, include_other)

    subplot_specs = []
    if include_wrist:
        if wrist_translation:
            subplot_specs.append(
                ("Wrist Translation", wrist_translation, "Position (m)", False)
            )
        if wrist_rotation:
            subplot_specs.append(
                (
                    "Wrist Rotation",
                    wrist_rotation,
                    f"Rotation ({unit})",
                    True,
                )
            )

    if include_fingers:
        for group_name, indices in finger_groups.items():
            subplot_specs.append(
                (
                    group_name,
                    indices,
                    f"Joint angle ({unit})",
                    True,
                )
            )

    if not subplot_specs:
        raise ValueError("No joint groups selected for plotting")

    fig_height = max(3.0, fig_height_per_row * len(subplot_specs))
    fig, axes = plt.subplots(
        len(subplot_specs),
        1,
        figsize=(fig_width, fig_height),
        sharex=True,
        squeeze=False,
    )
    axes_flat = axes.flatten()

    for ax, (title, indices, ylabel, convert_angles) in zip(axes_flat, subplot_specs):
        _plot_lines(
            ax=ax,
            frames=frames,
            qpos_array=qpos_array,
            joint_names=joint_names,
            joint_indices=indices,
            title=title,
            ylabel=ylabel,
            unit=unit,
            convert_angles=convert_angles,
        )

    fig.suptitle(
        f"Grouped qpos trajectories: {Path(pickle_path).name}",
        fontsize=14,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.985))

    output = Path(save_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=dpi)
    plt.close(fig)

    print(f"Loaded {num_frames} frames, {dof} qpos values per frame.")
    print(f"Saved grouped qpos curves to: {output}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot grouped wrist and finger qpos curves from an existing pickle."
    )
    parser.add_argument("pickle_file", type=str, help="Path to the retargeting pickle file")
    parser.add_argument(
        "--save",
        type=str,
        required=True,
        help="Output PNG path",
    )
    parser.add_argument(
        "--unit",
        choices=("rad", "deg"),
        default="rad",
        help="Angle unit for wrist rotation and finger joints",
    )
    parser.add_argument(
        "--no-wrist",
        action="store_true",
        help="Do not plot wrist translation/rotation subplots",
    )
    parser.add_argument(
        "--no-fingers",
        action="store_true",
        help="Do not plot finger joint subplots",
    )
    parser.add_argument(
        "--no-other",
        action="store_true",
        help="Hide joints that cannot be assigned to a known finger group",
    )
    parser.add_argument(
        "--fig-width",
        type=float,
        default=14.0,
        help="Figure width in inches",
    )
    parser.add_argument(
        "--fig-height-per-row",
        type=float,
        default=2.8,
        help="Figure height per subplot row in inches",
    )
    parser.add_argument("--dpi", type=int, default=150, help="Output image DPI")
    return parser.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    plot_grouped_qpos_curves(
        pickle_path=args.pickle_file,
        save_path=args.save,
        unit=args.unit,
        include_wrist=not args.no_wrist,
        include_fingers=not args.no_fingers,
        include_other=not args.no_other,
        fig_width=args.fig_width,
        fig_height_per_row=args.fig_height_per_row,
        dpi=args.dpi,
    )
